# SyncRoles
# Для работы плагина, нужно добавить право syncroles.sub в группу премки

# Токен бота
token: ""

# -----------------------------
# Данные вводить без скобок

# Айди роль сабки
premium_role_id:

# Айди сервера
server_id:

# Айди канала с интеракцией
channel_id:
